# Generated by Django 2.2.1 on 2019-06-10 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoerickeJoints',
            fields=[
                ('medicine', models.CharField(blank=True, max_length=75, null=True)),
                ('section', models.CharField(blank=True, max_length=100, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('wrd', models.CharField(blank=True, max_length=5, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'boericke_joints',
                'managed': False,
            },
        ),
    ]
