# Generated by Django 2.2.1 on 2019-06-10 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookName', models.CharField(blank=True, max_length=255, null=True)),
                ('medName', models.CharField(blank=True, max_length=255, null=True)),
                ('medDetails', models.TextField(blank=True, null=True)),
                ('Section', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
