# Generated by Django 2.2.1 on 2019-06-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicines',
            name='book_name',
            field=models.CharField(default='null', max_length=120),
            preserve_default=False,
        ),
    ]
