# Generated by Django 2.2.1 on 2019-06-06 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0002_medicines_book_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicines',
            name='book_name',
        ),
        migrations.RemoveField(
            model_name='medicines',
            name='med_details',
        ),
        migrations.RemoveField(
            model_name='medicines',
            name='med_name',
        ),
        migrations.AddField(
            model_name='medicines',
            name='bookName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='medicines',
            name='medDetails',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicines',
            name='medName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
