# Generated by Django 2.2.2 on 2019-06-26 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0002_medicines'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoerickConv',
            fields=[
                ('no_items', models.IntegerField(primary_key=True, serialize=False)),
                ('no_meds', models.IntegerField()),
                ('book_name', models.CharField(max_length=8)),
                ('med_name', models.CharField(max_length=41)),
                ('section', models.CharField(max_length=22)),
                ('med_details', models.CharField(max_length=3856)),
            ],
            options={
                'db_table': 'boerick_conv',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='BoerickeJoints',
        ),
    ]
